#!/usr/bin/env python3
"""Generate src/web/worldmap_svg.h from src/worldmap.h.

The header is a sequence of adjacent C string literals (one per row's
land runs), so it can be `#include`d inside a larger string-literal
context — the C/C++ preprocessor concatenates them.

Run once after editing src/worldmap.h:
    python3 scripts/gen_worldmap_svg.py
"""

from __future__ import annotations
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WM_H = ROOT / "src" / "worldmap.h"
OUT = ROOT / "src" / "web" / "worldmap_svg.h"


def parse_worldmap_h(text: str) -> tuple[int, int, bytes]:
    width = int(re.search(r"#define\s+WORLDMAP_W\s+(\d+)", text).group(1))
    height = int(re.search(r"#define\s+WORLDMAP_H\s+(\d+)", text).group(1))
    body = re.search(r"\{([^}]+)\}", text, re.DOTALL).group(1)
    bytes_ = bytes(
        int(b, 0) for b in re.findall(r"0x[0-9A-Fa-f]+", body)
    )
    return width, height, bytes_


def land_runs(width: int, height: int, bits: bytes):
    """Yield (y, x_start, run_length) for each horizontal run of land
    (bit=1) pixels. LSB-first per byte."""
    pitch = (width + 7) // 8  # bytes per row, but our format is row-major
                              # contiguous: ((y * width) + x) bit-indexed.
    for y in range(height):
        x = 0
        while x < width:
            # Skip ocean.
            while x < width:
                idx = y * width + x
                if (bits[idx >> 3] >> (idx & 7)) & 1:
                    break
                x += 1
            if x >= width:
                break
            run_start = x
            # Walk land run.
            while x < width:
                idx = y * width + x
                if not ((bits[idx >> 3] >> (idx & 7)) & 1):
                    break
                x += 1
            yield (y, run_start, x - run_start)


def main():
    text = WM_H.read_text()
    width, height, bits = parse_worldmap_h(text)
    expected = (width * height + 7) // 8
    if len(bits) != expected:
        sys.exit(f"size mismatch: bits={len(bits)} expected={expected}")

    runs = list(land_runs(width, height, bits))
    total_chars_estimate = sum(len(f"<rect x='{x}' y='{y}' width='{n}' height='1'/>") for y, x, n in runs)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        f.write("/*\n")
        f.write(" * Auto-generated by scripts/gen_worldmap_svg.py from src/worldmap.h.\n")
        f.write(f" * {width}x{height} bitmap → {len(runs)} <rect> runs (~{total_chars_estimate} bytes).\n")
        f.write(" * Adjacent C string literals — include inside a string-literal context.\n")
        f.write(" * Re-run the generator if src/worldmap.h changes.\n")
        f.write(" */\n")
        for y, x, n in runs:
            # `fill` defaults to ‘black’ in SVG; we override per-svg-context.
            f.write(f"\"<rect x='{x}' y='{y}' width='{n}' height='1'/>\"\n")
    print(f"wrote {OUT} — {len(runs)} runs, ~{total_chars_estimate} bytes of SVG content")


if __name__ == "__main__":
    main()
